### ISSUE TITLE
Experimental RichText Support

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#37]
This issue serves as a master issue for initial / experimental RichTextSupport for Convergence.

# Goals
The goal is to build a robust core rich text data model that can be adapted to multiple rich text editors including:

- Slate
- CKEditor 5
- Draft
- Quill

# Tasks
- [ ] Design core rich text data model.
- [ ] Prototype core rich text data model.
- [ ] Validate adaptation methodology for Quill, Slate, CK5, and Draft.
- [ ] Design RealTimeRichTextDocument.
- [ ] Prototype RealTimeRichTextDocument.
- [ ] Design Rich Text References.
- [ ] Prototype Rich Text References.
- [ ] Design rich text operations.
- [ ] Design rich text transformations.
- [ ] Design new protocol messages.
- [ ] Prototype new protocol messages.
- [ ] Prototype operations and transformation functions in client.
- [ ] Prototype operations and transformation functions in server.
- [ ] Test
- [ ] Docs

# Design
TBD

# API
TBD

**Comment by edudant** [comment]
Hi, I am looking forward for the rich text support! Your current list mentions only editors with abstracted data model. Will you support also HTML based editors like CK4, Summernote or Froala in the future?

**Comment by mmacfadden** [comment]
Thanks for the comment. This issue is specifically around structure rich text. We have rudimentary support for HTML based editors using our Dom Utils.  There is a Froala example here:

https://github.com/convergencelabs/javascript-examples/tree/master/src/examples/froala
