### ISSUE TITLE
1.0.0 Rest API Review and Changes

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#80]
The REST API was originally intended only to support the admin console.  Subsequently it has now been exposed to end users of the system as an integration mechanism.  We need to review the REST API, fix inconsistencies, and fix several issues.

- [ ] **Use PagedData for REST API**: Several rest calls that support paging do not return the PagedData structure. (#4)
- [ ] **Model PUT**: The model PUT REST call does not work for existing models. It does not appropriately update meta-data and operation history, and does not work at all for open models. (#79)
- [ ] **JSON API Spect**: Investigate JSON API. (#128)
